[package]
name = "hex_overmind_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "2.1.0"
flatbuffers = "23.5.26"
rmp = "0.8.11"
